<script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.js"></script>
<script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.js"></script>
{{ HTML::script('js/bootstrap-datepicker.js'); }}
<script type="text/javascript" src="//code.angularjs.org/1.3.8/angular.js"></script>
<script type="text/javascript" src="//code.angularjs.org/1.3.8/angular-route.js"></script>
<script type="text/javascript" src="//code.angularjs.org/1.3.8/angular-sanitize.js"></script>
<script type="text/javascript" src="//code.angularjs.org/1.3.8/angular-animate.js"></script>
<script type="text/javascript" src="//raw.githubusercontent.com/siddii/angular-timer/master/dist/angular-timer.min.js"></script>
{{ HTML::script('angular/angular_modules/angular-ng-flow/ng-flow-standalone.js'); }}
{{ HTML::style('css/bootstrap-united.min.css'); }}
{{ HTML::style('css/bootstrap-datepicker.css'); }}
{{ HTML::style('css/font-awesome.min.css'); }}
{{ HTML::style('css/style.css'); }}